HEAD_DAMAGE_MODIFIER = 3
BODY_DAMAGE_MODIFIER = 2
ARMS_DAMAGE_MODIFIER = 1.2
LEGS_DAMAGE_MODIFIER = 1.2

HEAD_HIT_MODIFIER = 0.5
BODY_HIT_MODIFIER = 2
ARMS_HIT_MODIFIER = 1.4
LEGS_HIT_MODIFIER = 1.2

CHEAP_ROOM_LUCK_MODIFIER = 5
WELL_MAINTAINED_ROOM_LUCK_MODIFIER = 8
LUXURY_ROOM_LUCK_MODIFIER = 15

CHEAP_ROOM_ROB_PERCENTAGE = 20
WELL_MAINTAINED_ROOM_ROB_PERCENTAGE = 30
LUXURY_ROOM_ROB_PERCENTAGE = 40
